HW1
eclimov/practice-vue-js pull request #1
Opened 2020-01-23 10:56 UTC by tzatushevskaya

- Added image
 - Added homework1.html file to new directory

2020-01-23 18:56 UTC, eclimov requested changes
Also, please, remove/replace that 'image.jpg', as it is not part of the task.

2020-01-23 18:56 UTC, eclimov commented on public/Sjofn/homework1.html
> +                    <li>- Section 3. Pick one of items and provide some information for it, in 2-3 sentences in a paragraph. Highlight 3 important words/phrases with special color, ‘underline’ and ‘b
![pic1](https://user-images.githubusercontent.com/16742190/73011755-8e43c080-3e1d-11ea-9cd9-7aa6b9adcdb6.JPG)
Please, check the screenshot. Many symbols are displayed incorrectly (Chrome browser). 
Looks like a good opportunity to use `<meta>` tag with encoding provided:
https://www.w3schools.com/tags/att_meta_charset.asp

2020-01-23 18:56 UTC, eclimov commented on public/Sjofn/homework1.html
> +        <li><a href="https://en.wikipedia.org/wiki/Scala_(programming_language)">Scala</a></li>
According to the requirements, a link should open in a new tab. Please, check '_target_' attribute:
https://www.w3schools.com/tags/att_a_target.asp

2020-01-23 18:56 UTC, eclimov commented on public/Sjofn/homework1.html
> +    function alllert(){
Please, name the function with a more accurate name and follow the task

2020-01-23 18:56 UTC, eclimov commented on public/Sjofn/homework1.html
> +</html>
As you see, 'Github' has marked this file with a 'warning' icon. It is suggested to always have an empty line at the end of a file.
You may automate this, - please, enable this configuration in your IDE:
https://stackoverflow.com/questions/36019534/add-an-empty-line-at-end-of-file-according-to-psr-2-on-phpstorm

2020-01-23 18:56 UTC, eclimov commented on public/Sjofn/homework1.html
> +            background-color: cadetblue;
I suggest you to not change background color of a simple button, - a default one looks more natural.

2020-01-23 18:56 UTC, eclimov commented on public/Sjofn/homework1.html
> +        #myId{
Please, provide accurate and clear names to IDs, classes, etc.

2020-01-23 18:56 UTC, eclimov commented on public/Sjofn/homework1.html
> +            size: A3;
Doesn't look like this property really affects anything on the page. 
If you want to change size of font, better use `font-size` property.

2020-01-23 18:56 UTC, eclimov commented on public/Sjofn/homework1.html
> +                    <li>- Section 5. Pick a palette, make picture of it, put it in the same directory as the HTML file and display it in this section of the page. Add ‘Palette’ title to the image</li
Please, implement this point as well.
Don't forget about `title` attribute.

2020-01-23 18:56 UTC, eclimov commented on public/Sjofn/homework1.html
> +                    <li>- Section 4. Add button [Name](should output your first name in console).<br>
Please, implement this point as well.

2020-01-23 18:56 UTC, eclimov commented on public/Sjofn/homework1.html
> +                    <li>- A page contains different ‘div’ sections. Each one starts with corresponding heading and ends with ‘hr’</li>
Please, implement this point as well.

2020-01-23 18:56 UTC, eclimov commented on public/Sjofn/homework1.html
> +        .myClass{
Please, provide accurate and clear names to IDs, classes, etc.
'_section1_' class name would be better in this case.

2020-01-23 18:56 UTC, eclimov commented on public/Sjofn/homework1.html
> +        .myClass{
You may also provide a class name or an ID to each section, - it would make the HTML more clear to a reader.

2020-01-23 18:56 UTC, eclimov commented on public/Sjofn/homework1.html
> +<button id="myId" onclick="alllert()">Check if you are a bad tester!</button>
Don't forget to put your buttons in a separate `div`.

2020-01-23 18:56 UTC, eclimov commented on public/Sjofn/homework1.html
> +            width: 300px;
According to the task, you should set **max width** of the div

2020-01-23 18:56 UTC, eclimov commented on public/Sjofn/homework1.html
> +    <br/>“The <b>complexity</b> of building backends today is just out of control. It’s infrastructure, it’s deployment, it’s APIs… Dark is about removing all this complexity,” Biggar said.
According to the task, it is required to 

> Highlight 3 important words/phrases with special color, ‘underline’ and ‘bold’ styles, accordingly

You have used only bold style at the moment. Please, apply the remaining styles somewhere in the text as well.

2020-01-23 19:04 UTC, eclimov commented
Since it is **homework 2**, please also do the following, according to the requirements:

> Update 'README.md' with task of previous homework

2020-01-27 19:04 UTC, eclimov commented on public/Sjofn/homework1.html
> +                    <li>- A page contains different ‘div’ sections. Each one starts with corresponding heading and ends with ‘hr’</li>
Don't forget about heading in each section

2020-01-27 19:06 UTC, eclimov commented on public/Sjofn/homework1.html
> +        .myClass{
Please, remove unused class

2020-01-27 19:10 UTC, eclimov commented on public/Sjofn/homework1.html
> +<div  id="section_3">
This section should have maximum width 300px

2020-01-27 19:12 UTC, eclimov commented on public/Sjofn/homework1.html
> +<div  id="section_5">
This section should contain only a picture of palette

2020-01-29 19:03 UTC, eclimov commented on public/Sjofn/homework1.html
> +<div  id="section_5">
Looks like you forgot to add and commit the picture. Please, check.

2020-01-30 10:55 UTC, eclimov approved these changes
Well done!

2020-01-30 10:55 UTC, SandaPanteleimonov reviewed
This is brilliant! Approved 100!

2020-01-30 10:56 UTC, eclimov approved these changes

2020-01-30 10:56 UTC, SandaPanteleimonov approved these changes

2020-01-30 10:57 UTC, merged