Pr4 1 sjofn
eclimov/practice-vue-js pull request #10
Opened 2020-02-20 13:25 UTC by tzatushevskaya

I've done the task! :) Please review!

2020-02-20 17:31 UTC, eclimov requested changes
Nice! 
Only a few things need to be fixed. Please, check.

2020-02-20 17:32 UTC, eclimov commented on public/Sjofn/practice/sjofn4.html
> +<!--<button onclick="instruction1()">Open console and click me</button>-->
Please, remove this commented line. 
It is usually considered a bad practice to leave commented instructions/markup.

2020-02-20 17:36 UTC, eclimov commented on public/Sjofn/practice/sjofn4.html
> +    let z = prompt("z = ", " ");
It is really cool that you've found a way to receive input via `prompt`, but, unfortunately, it wasn't required by the task. 
Please, remove all of the instructions, except the functions (according to the task's description).

2020-02-20 17:36 UTC, eclimov commented on public/Sjofn/practice/sjofn4.html
> +    //getDatetime();
Please, remove all of the instructions, except the functions (according to the task's description).

2020-02-20 17:36 UTC, eclimov commented on public/Sjofn/practice/sjofn4.html
> +    //getPowFive(z);
Please, remove all of the instructions, except the functions (according to the task's description).

2020-02-20 17:36 UTC, eclimov commented on public/Sjofn/practice/sjofn4.html
> +    let a = prompt("a = ", " "), b = prompt("b = ", " ");
Please, remove all of the instructions, except the functions (according to the task's description).

2020-02-20 17:36 UTC, eclimov commented on public/Sjofn/practice/sjofn4.html
> +    //getSumAndDivide(a, b);
Please, remove all of the instructions, except the functions (according to the task's description).

2020-02-20 17:36 UTC, eclimov commented on public/Sjofn/practice/sjofn4.html
> +    let m = prompt("m = ", " "), n = prompt("n = ", " "), l = prompt("l = ", " "), p = prompt("p = ", " ");
Please, remove all of the instructions, except the functions (according to the task's description).

2020-02-20 17:37 UTC, eclimov commented on public/Sjofn/practice/sjofn4.html
> +    finalCalculations(m, n, l, p);
Please, remove all of the instructions, except the functions (according to the task's description).

2020-02-20 17:38 UTC, eclimov commented on public/Sjofn/practice/sjofn4.html
> +    //getDatetime();
Also, please, leave an empty line between functions, - it would make the code more segmented and, therefore, readable.

2020-02-20 17:44 UTC, eclimov commented on public/Sjofn/practice/sjofn4.html
> +        console.log(new Date());
`new Date()` contains unformatted object:

> Thu Feb 20 2020 19:41:12 GMT+0200 (Восточная Европа, стандартное время)

But there is a way to format the datetime and transform it to a readable string before printing it - `new Date().toLocaleString()`:

> 20.02.2020, 19:41:01

P.S.: it's just for your information, - no need to change anything here if you don't want to.

2020-02-24 19:08 UTC, eclimov commented on public/Sjofn/practice/sjofn4.html
> +    function getPowFive(z) {
Please, leave an emply line between functions. 
It is a good practice and makes the code more readable.

2020-02-25 11:19 UTC, eclimov approved these changes
Good job!

2020-02-25 11:19 UTC, SandaPanteleimonov approved these changes
Everything is super cool.

2020-02-25 11:20 UTC, merged