Pr4-4
eclimov/practice-vue-js pull request #14
Opened 2020-03-03 16:28 UTC by SandaPanteleimonov

Following merge includes addition of new object and array.
Functions were removed.
Function definitions modified.

2020-03-03 20:17 UTC, eclimov commented on README.md
> +<!DOCTYPE html>
Updates in this file were not required by the task.
Looks like you have accidentally committed it.
Please, rollback the changes.

2020-03-03 20:17 UTC, eclimov commented on public/hw2-united.html
> +            <img title="colorpalette" src="sanda/practice/palette.png" alt="You have Internet Explorer, sorry" id="palette">
Updates in this file were not required by the task.

2020-03-03 20:17 UTC, eclimov commented on public/index.html
> +      <img title="colorpalette" src="sanda/practice/palette.png" alt="You have Internet Explorer, sorry" id="palette">
Updates in this file were not required by the task.

2020-03-03 20:18 UTC, eclimov commented on public/sanda/practice/hw3.html
> +        <td><img src="../assets/castor.jfif" alt="Castor"></td>
Updates in this file were not required by the task.

2020-03-03 20:18 UTC, eclimov requested changes
Please, revert unnecessary changes.

2020-03-04 10:19 UTC, eclimov approved these changes
Good job. Approved.

2020-03-04 13:22 UTC, tzatushevskaya approved these changes

2020-03-04 19:13 UTC, merged